<a href="https://colab.research.google.com/github/ItokianaMahenintsoa/python-data-analysis/blob/main/Data_Analysis_Data_Loading%2C_Storage%2C_File_Format_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("sample_data/ex1.csv")
df

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [3]:
pd.read_csv("sample_data/ex2.csv", header=None)

   0   1   2   3      4
0  1   2   3   4  hello
1  5   6   7   8  world
2  9  10  11  12    foo

In [4]:
pd.read_csv("sample_data/ex2.csv", names=["a", "b", "c", "d", "message"])

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [5]:
names = ["a", "b", "c", "d", "message"]

In [6]:
pd.read_csv("sample_data/ex2.csv", names=names, index_col="message")

         a   b   c   d
message
hello    1   2   3   4
world    5   6   7   8
foo      9  10  11  12

In [7]:
!cat sample_data/csv_mindex.csv

key1,key2,value1,value2
one,a,1,2
one,b,3,4
one,c,5,6
one,d,7,8
two,a,9,10
two,b,11,12
two,c,13,14
two,d,15,16

In [8]:
parsed = pd.read_csv("sample_data/csv_mindex.csv", index_col=["key1", "key2"])
parsed

           value1  value2
key1 key2
one  a          1       2
     b          3       4
     c          5       6
     d          7       8
two  a          9      10
     b         11      12
     c         13      14
     d         15      16

In [9]:
!cat sample_data/ex3.txt

            A         B         C
aaa -0.264438 -1.026059 -0.619500
bbb  0.927272  0.302904 -0.032399
ccc -0.264273 -0.386314 -0.217601
ddd -0.871858 -0.348382  1.100491

In [10]:
result = pd.read_csv("sample_data/ex3.txt", sep="\s+")
result

<>:1: SyntaxWarning: invalid escape sequence '\s'
<>:1: SyntaxWarning: invalid escape sequence '\s'
/tmp/ipykernel_3056/2293783763.py:1: SyntaxWarning: invalid escape sequence '\s'
  result = pd.read_csv("sample_data/ex3.txt", sep="\s+")

            A         B         C
aaa -0.264438 -1.026059 -0.619500
bbb  0.927272  0.302904 -0.032399
ccc -0.264273 -0.386314 -0.217601
ddd -0.871858 -0.348382  1.100491

In [11]:
!cat sample_data/ex4.csv

# hey!
a,b,c,d,message
# just wanted to make things more difficult for you
# who reads CSV files with computers, anyway?
1,2,3,4,hello
5,6,7,8,world
9,10,11,12,foo

In [12]:
pd.read_csv("sample_data/ex4.csv", skiprows=[0,2,3])

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [13]:
!cat sample_data/ex5.csv

something,a,b,c,d,message
one,1,2,3,4,NA
two,5,6,,8,world
three,9,10,11,12,foo

In [14]:
result = pd.read_csv("sample_data/ex5.csv")
result

  something  a   b     c   d message
0       one  1   2   3.0   4     NaN
1       two  5   6   NaN   8   world
2     three  9  10  11.0  12     foo

In [15]:
pd.isna(result)

   something      a      b      c      d  message
0      False  False  False  False  False     True
1      False  False  False   True  False    False
2      False  False  False  False  False    False

In [16]:
result = pd.read_csv("sample_data/ex5.csv", na_values=["NULL"])
result

  something  a   b     c   d message
0       one  1   2   3.0   4     NaN
1       two  5   6   NaN   8   world
2     three  9  10  11.0  12     foo

In [17]:
result2 = pd.read_csv("sample_data/ex5.csv", keep_default_na=False)
result2

  something  a   b   c   d message
0       one  1   2   3   4      NA
1       two  5   6       8   world
2     three  9  10  11  12     foo

In [18]:
result2.isna()

   something      a      b      c      d  message
0      False  False  False  False  False    False
1      False  False  False  False  False    False
2      False  False  False  False  False    False

In [19]:
result3 = pd.read_csv("sample_data/ex5.csv", keep_default_na=False, na_values=["NA"])
result3

  something  a   b   c   d message
0       one  1   2   3   4     NaN
1       two  5   6       8   world
2     three  9  10  11  12     foo

In [20]:
result3.isna()

   something      a      b      c      d  message
0      False  False  False  False  False     True
1      False  False  False  False  False    False
2      False  False  False  False  False    False

In [21]:
sentinels = {"message": ["foo", "NA"], "something": ["two"]}

In [22]:
pd.read_csv("sample_data/ex5.csv", na_values=sentinels, keep_default_na=False)

  something  a   b   c   d message
0       one  1   2   3   4     NaN
1       NaN  5   6       8   world
2     three  9  10  11  12     NaN

In [23]:
pd.options.display.max_rows = 10

In [25]:
result = pd.read_csv("sample_data/ex6.csv")
result

           one       two     three      four key
0     0.467976 -0.038649 -0.295344 -1.824726   L
1    -0.358893  1.404453  0.704965 -0.200638   B
2    -0.501840  0.659254 -0.421691 -0.057688   G
3     0.204886  1.074134  1.388361 -0.982404   R
4     0.354628 -0.133116  0.283763 -0.837063   Q
...        ...       ...       ...       ...  ..
9995  2.311896 -0.417070 -1.409599 -0.515821   L
9996 -0.479893 -0.650419  0.745152 -0.646038   E
9997  0.523331  0.787112  0.486066  1.093156   K
9998 -0.362559  0.598894 -1.843201  0.887292   G
9999 -0.096376 -1.012999 -0.657431 -0.573315   0

[10000 rows x 5 columns]

In [27]:
pd.read_csv("sample_data/ex6.csv", nrows=5)

        one       two     three      four key
0  0.467976 -0.038649 -0.295344 -1.824726   L
1 -0.358893  1.404453  0.704965 -0.200638   B
2 -0.501840  0.659254 -0.421691 -0.057688   G
3  0.204886  1.074134  1.388361 -0.982404   R
4  0.354628 -0.133116  0.283763 -0.837063   Q

In [29]:
chunker = pd.read_csv("sample_data/ex6.csv", nrows=1000)

In [30]:
type(chunker)

pandas.core.frame.DataFrame

In [31]:
chunker = pd.read_csv("sample_data/ex6.csv", chunksize=1000)

In [32]:
tot = pd.Series([], dtype='int64')

In [33]:
for piece in chunker:
    tot = tot.add(piece["key"].value_counts(), fill_value=0)

In [34]:
tot = tot.sort_values(ascending=False)
tot[:10]

key
E    368.0
X    364.0
L    346.0
O    343.0
Q    340.0
M    338.0
J    337.0
F    335.0
K    334.0
H    330.0
dtype: float64

In [35]:
data = pd.read_csv("sample_data/ex5.csv")
data

  something  a   b     c   d message
0       one  1   2   3.0   4     NaN
1       two  5   6   NaN   8   world
2     three  9  10  11.0  12     foo

In [36]:
data.to_csv("sample_data/out.csv")

In [38]:
!cata sample_data/out.csv

/bin/bash: line 1: cata: command not found

In [39]:
import sys

In [40]:
data.to_csv(sys.stdout, sep="|")

|something|a|b|c|d|message
0|one|1|2|3.0|4|
1|two|5|6||8|world
2|three|9|10|11.0|12|foo

In [41]:
data.to_csv(sys.stdout, na_rep="NULL")

,something,a,b,c,d,message
0,one,1,2,3.0,4,NULL
1,two,5,6,NULL,8,world
2,three,9,10,11.0,12,foo

In [42]:
data.to_csv(sys.stdout, index=False, header=False)

one,1,2,3.0,4,
two,5,6,,8,world
three,9,10,11.0,12,foo

In [43]:
data.to_csv(sys.stdout, index=False, columns=["a", "b", "c"])

a,b,c
1,2,3.0
5,6,
9,10,11.0

In [45]:
!cat sample_data/ex7.csv

"a","b","c"
"1","2","3"
"1","2","3"

In [46]:
import csv

In [48]:
f = open("sample_data/ex7.csv")

In [49]:
reader = csv.reader(f)

In [50]:
for line in reader:
    print(line)

['a', 'b', 'c']
['1', '2', '3']
['1', '2', '3']

In [51]:
f.close()

In [52]:
with open("sample_data/ex7.csv") as f:
  lines = list(csv.reader(f))

In [53]:
header, values = lines[0], lines[1:]

In [54]:
data_dict = {h: v for h, v in zip(header, zip(*values))}
data_dict

{'a': ('1', '1'), 'b': ('2', '2'), 'c': ('3', '3')}

In [55]:
class my_dialect(csv.Dialect):
  lineterminator= "\n"
  delimiter = ";"
  quotechar = '"'
  quoting = csv.QUOTE_MINIMAL

In [57]:
obj = """
{"name": "Wes", "cities_lived": ["Akron", "Nashville", "New York", "San Francisco"], "pet": null, "siblings": [{"name": "Scott", "age": 34, "hobbies": ["guitars", "soccer"]},
{"name": "Katie", "age": 42, "hobbies": ["diving", "art"]}]}
"""

In [58]:
import json

In [59]:
result = json.loads(obj)
result

{'name': 'Wes',
 'cities_lived': ['Akron', 'Nashville', 'New York', 'San Francisco'],
 'pet': None,
 'siblings': [{'name': 'Scott', 'age': 34, 'hobbies': ['guitars', 'soccer']},
  {'name': 'Katie', 'age': 42, 'hobbies': ['diving', 'art']}]}

In [60]:
asjson = json.dumps(result)
asjson

'{"name": "Wes", "cities_lived": ["Akron", "Nashville", "New York", "San Francisco"], "pet": null, "siblings": [{"name": "Scott", "age": 34, "hobbies": ["guitars", "soccer"]}, {"name": "Katie", "age": 42, "hobbies": ["diving", "art"]}]}'

In [61]:
siblings = pd.DataFrame(result["siblings"], columns=["name", "age"])
siblings

    name  age
0  Scott   34
1  Katie   42

In [63]:
!cat sample_data/example.json

[{"a": 1, "b": 2, "c": 3},
 {"a": 4, "b": 5, "c": 6},
 {"a": 7, "b": 8, "c": 9}]

In [65]:
data = pd.read_json("sample_data/example.json")
data

   a  b  c
0  1  2  3
1  4  5  6
2  7  8  9

In [66]:
data.to_json(sys.stdout)

{"a":{"0":1,"1":4,"2":7},"b":{"0":2,"1":5,"2":8},"c":{"0":3,"1":6,"2":9}}

In [67]:
data.to_json(sys.stdout, orient="records")

[{"a":1,"b":2,"c":3},{"a":4,"b":5,"c":6},{"a":7,"b":8,"c":9}]

In [69]:
!pip install lxml beautifulsoup4 html5lib

Requirement already satisfied: lxml in /usr/local/lib/python3.12/dist-packages (6.0.2)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.12/dist-packages (4.13.5)
Requirement already satisfied: html5lib in /usr/local/lib/python3.12/dist-packages (1.1)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4) (2.8.3)
Requirement already satisfied: typing-extensions>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4) (4.15.0)
Requirement already satisfied: six>=1.9 in /usr/local/lib/python3.12/dist-packages (from html5lib) (1.17.0)
Requirement already satisfied: webencodings in /usr/local/lib/python3.12/dist-packages (from html5lib) (0.5.1)

In [71]:
tables = pd.read_html('sample_data/fdic_failed_bank_list.html')
len(tables)

1

In [72]:
failures = tables[0]
failures.head()

,Bank Name,City,ST,CERT,Acquiring Institution,Closing Date,Updated Date
0,Allied Bank,Mulberry,AR,91,Today's Bank,"September 23, 2016","November 17, 2016"
1,The Woodbury Banking Company,Woodbury,GA,11297,United Bank,"August 19, 2016","November 17, 2016"
2,First CornerStone Bank,King of Prussia,PA,35312,First-Citizens Bank & Trust Company,"May 6, 2016","September 6, 2016"
3,Trust Company Bank,Memphis,TN,9956,The Bank of Fayette County,"April 29, 2016","September 6, 2016"
4,North Milwaukee State Bank,Milwaukee,WI,20364,First-Citizens Bank & Trust Company,"March 11, 2016","June 16, 2016"

In [73]:
close_timestamps = pd.to_datetime(failures["Closing Date"])
close_timestamps.dt.year.value_counts()

Closing Date
2010    157
2009    140
2011     92
2012     51
2008     25
       ...
2004      4
2001      4
2007      3
2003      3
2000      2
Name: count, Length: 15, dtype: int64

In [74]:
from lxml import objectify

In [77]:
path = "datasets/mta_perf/Performance_MNR.xml"

In [78]:
with open(path) as f :
  parsed = objectify.parse(f)

In [79]:
root = parsed.getroot()

In [80]:
data = []

In [81]:
skip_fields = ["PARENT_SEQ", "INDICATOR_SEQ", "DESIRED_CHANGE", "DECIMAL_PLACES"]

In [82]:
for elt in root.INDICATOR:
  el_data = {}
  for child in elt.getchildren():
    if child.tag in skip_fields:
      continue
    el_data[child.tag] = child.pyval
  data.append(el_data)

In [84]:
perf = pd.DataFrame(data)
perf.head()

,AGENCY_NAME,INDICATOR_NAME,DESCRIPTION,PERIOD_YEAR,PERIOD_MONTH,CATEGORY,FREQUENCY,INDICATOR_UNIT,YTD_TARGET,YTD_ACTUAL,MONTHLY_TARGET,MONTHLY_ACTUAL
0,Metro-North Railroad,On-Time Performance (West of Hudson),Percent of commuter trains that arrive at thei...,2008,1,Service Indicators,M,%,95.0,96.9,95.0,96.9
1,Metro-North Railroad,On-Time Performance (West of Hudson),Percent of commuter trains that arrive at thei...,2008,2,Service Indicators,M,%,95.0,96.0,95.0,95.0
2,Metro-North Railroad,On-Time Performance (West of Hudson),Percent of commuter trains that arrive at thei...,2008,3,Service Indicators,M,%,95.0,96.3,95.0,96.9
3,Metro-North Railroad,On-Time Performance (West of Hudson),Percent of commuter trains that arrive at thei...,2008,4,Service Indicators,M,%,95.0,96.8,95.0,98.3
4,Metro-North Railroad,On-Time Performance (West of Hudson),Percent of commuter trains that arrive at thei...,2008,5,Service Indicators,M,%,95.0,96.6,95.0,95.8

In [85]:
perf2 = pd.read_xml(path)
perf2.head()

,INDICATOR_SEQ,PARENT_SEQ,AGENCY_NAME,INDICATOR_NAME,DESCRIPTION,PERIOD_YEAR,PERIOD_MONTH,CATEGORY,FREQUENCY,DESIRED_CHANGE,INDICATOR_UNIT,DECIMAL_PLACES,YTD_TARGET,YTD_ACTUAL,MONTHLY_TARGET,MONTHLY_ACTUAL
0,28445,NaN,Metro-North Railroad,On-Time Performance (West of Hudson),Percent of commuter trains that arrive at thei...,2008,1,Service Indicators,M,U,%,1,95.00,96.90,95.00,96.90
1,28445,NaN,Metro-North Railroad,On-Time Performance (West of Hudson),Percent of commuter trains that arrive at thei...,2008,2,Service Indicators,M,U,%,1,95.00,96.00,95.00,95.00
2,28445,NaN,Metro-North Railroad,On-Time Performance (West of Hudson),Percent of commuter trains that arrive at thei...,2008,3,Service Indicators,M,U,%,1,95.00,96.30,95.00,96.90
3,28445,NaN,Metro-North Railroad,On-Time Performance (West of Hudson),Percent of commuter trains that arrive at thei...,2008,4,Service Indicators,M,U,%,1,95.00,96.80,95.00,98.30
4,28445,NaN,Metro-North Railroad,On-Time Performance (West of Hudson),Percent of commuter trains that arrive at thei...,2008,5,Service Indicators,M,U,%,1,95.00,96.60,95.00,95.80

In [86]:
frame = pd.read_csv("sample_data/ex1.csv")
frame

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [87]:
frame.to_pickle("sample_data/frame_pickle")

In [88]:
pd.read_pickle("sample_data/frame_pickle")

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [90]:
xlsx = pd.ExcelFile("sample_data/ex1.xlsx")
xlsx.sheet_names

['Sheet1']

In [91]:
xlsx.parse(sheet_names="Sheet1")

   Unnamed: 0  a   b   c   d message
0           0  1   2   3   4   hello
1           1  5   6   7   8   world
2           2  9  10  11  12     foo

In [92]:
xlsx.parse(sheet_name="Sheet1", index_col=0)

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [93]:
frame = pd.read_excel("sample_data/ex1.xlsx", sheet_name="Sheet1")
frame

   Unnamed: 0  a   b   c   d message
0           0  1   2   3   4   hello
1           1  5   6   7   8   world
2           2  9  10  11  12     foo

In [94]:
writer = pd.ExcelWriter("sample_data/ex2.xlsx")

In [95]:
frame.to_excel(writer, "Sheet1")

/tmp/ipykernel_3056/2112036528.py:1: FutureWarning: Starting with pandas version 3.0 all arguments of to_excel except for the argument 'excel_writer' will be keyword-only.
  frame.to_excel(writer, "Sheet1")

In [97]:
writer.close()

In [98]:
frame.to_excel("sample_data/ex2.xlsx")

In [100]:
import numpy as np

In [101]:
frame = pd.DataFrame({"a": np.random.standard_normal(100)})

In [102]:
store = pd.HDFStore("sample_data/my_data.h5")

In [103]:
store["obj1"] = frame

In [104]:
store["obj1_col"] = frame["a"]
store

<class 'pandas.io.pytables.HDFStore'>
File path: sample_data/my_data.h5

In [105]:
store["obj1"]

           a
0  -0.768401
1  -0.241571
2  -0.192229
3  -0.096125
4  -0.436791
..       ...
95 -0.089182
96 -0.103969
97 -0.616077
98  0.183595
99 -2.465950

[100 rows x 1 columns]

In [106]:
store.put("obj2", frame, format="table")
store.select("obj2", where=["index >= 10 and index <= 15"])

           a
10  0.142420
11  0.811586
12 -1.307797
13 -0.684353
14  0.087692
15  0.233309

In [107]:
store.close()

In [110]:
frame.to_hdf("sample_data/mydata.h5", "obj3", format="table")

/tmp/ipykernel_3056/3808265857.py:1: FutureWarning: Starting with pandas version 3.0 all arguments of to_hdf except for the argument 'path_or_buf' will be keyword-only.
  frame.to_hdf("sample_data/mydata.h5", "obj3", format="table")

In [112]:
pd.read_hdf("sample_data/mydata.h5", "obj3", where=["index<5"])

          a
0 -0.768401
1 -0.241571
2 -0.192229
3 -0.096125
4 -0.436791

In [113]:
import os

In [114]:
os.remove("sample_data/mydata.h5")

In [115]:
import requests

In [116]:
url = "https://api.github.com/repos/pandas-dev/pandas/issues"

In [117]:
resp = requests.get(url)

In [118]:
resp.raise_for_status()

In [120]:
resp

In [121]:
data = resp.json()

In [122]:
data[0]["title"]

'BUG: pd.Series inconsistently converts dtype=str to object vs pd.array'

In [123]:
issues = pd.DataFrame(data, columns=["number", "title", "labels", "state"])
issues

,number,title,labels,state
0,64558,BUG: pd.Series inconsistently converts dtype=s...,[],open
1,64556,PERF: vectorize year/month extraction for obje...,[],open
2,64555,PERF: dates.apply(lambda x: 100 * x.year + x.m...,"[{'id': 8935311, 'node_id': 'MDU6TGFiZWw4OTM1M...",open
3,64554,TYP: Add return type annotations to DataFrame/...,[],open
4,64553,DOC: Fix typos and misleading See Also descrip...,[],open
...,...,...,...,...
25,64528,ENH: Check type of objects in assert_series_equal,"[{'id': 76812, 'node_id': 'MDU6TGFiZWw3NjgxMg=...",open
26,64525,TST: Add test for bug (#64524) that causes `re...,[],open
27,64524,BUG: `read_html` parses nested table incorrect...,"[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...",open
28,64515,PERF: Use SIMD for read_csv C tokenizer,"[{'id': 8935311, 'node_id': 'MDU6TGFiZWw4OTM1M...",open
29,64513,PERF: Use lookup table for fast bulk scanning ...,"[{'id': 8935311, 'node_id': 'MDU6TGFiZWw4OTM1M...",open

In [124]:
import sqlite3

In [129]:
query = """ CREATE TABLE test (a VARCHAR(20), b VARCHAR(20), c REAL, d INTEGER);"""

In [130]:
con = sqlite3.connect("mydata.sqlite")
con.execute(query)

In [131]:
con.commit()

In [132]:
data = [("Atlanta", "Georgia", 1.25, 6), ("Tallahassee", "Florida", 2.6, 3), ("Sacramento", "California", 1.7, 5)]

In [133]:
stmt = "INSERT INTO test VALUES(?, ?, ?, ?)"

In [134]:
con.executemany(stmt, data)

In [136]:
con.commit()

In [137]:
cursor = con.execute("SELECT * FROM test")

In [138]:
rows = cursor.fetchall()
rows

[('Atlanta', 'Georgia', 1.25, 6),
 ('Tallahassee', 'Florida', 2.6, 3),
 ('Sacramento', 'California', 1.7, 5)]

In [139]:
cursor.description

(('a', None, None, None, None, None, None),
 ('b', None, None, None, None, None, None),
 ('c', None, None, None, None, None, None),
 ('d', None, None, None, None, None, None))

In [141]:
pd.DataFrame(rows, columns=[x[0] for x in cursor.description])

             a           b     c  d
0      Atlanta     Georgia  1.25  6
1  Tallahassee     Florida  2.60  3
2   Sacramento  California  1.70  5

In [143]:
!pip install sqlalchemy

Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.12/dist-packages (2.0.48)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (3.3.2)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (4.15.0)

In [144]:
import sqlalchemy as sqla

In [145]:
db = sqla.create_engine("sqlite:///mydata.sqlite")

In [146]:
pd.read_sql("SELECT * FROM test", db)

             a           b     c  d
0      Atlanta     Georgia  1.25  6
1  Tallahassee     Florida  2.60  3
2   Sacramento  California  1.70  5